"use client";

import React, { useState, useEffect } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import {
    Collapsible,
    CollapsibleContent,
    CollapsibleTrigger,
} from "@/components/ui/collapsible";
import {
    ArrowLeft,
    FileText,
    Save,
    Download,
    ChevronDown,
    ChevronRight,
    Shield,
    Building2,
    RefreshCw,
    CheckCircle2,
    AlertCircle,
    Info,
    Server,
} from "lucide-react";
import Link from "next/link";
import { format } from 'date-fns';
import { de } from 'date-fns/locale';

interface DocumentationSection {
    id: string;
    title: string;
    description: string;
    content: string;
    isAutoGenerated?: boolean;
}

interface SystemInfo {
    softwareName: string;
    softwareVersion: string;
    databaseType: string;
    features: string[];
    lastUpdated: string;
}

interface DocumentationContent {
    companyName: string;
    companyAddress: string;
    taxNumber: string;
    responsiblePerson: string;
    sections: DocumentationSection[];
    systemInfo: SystemInfo;
    createdAt?: string;
    updatedAt?: string;
}

interface DocumentationData {
    id: number | null;
    version: string;
    title: string;
    content: DocumentationContent;
    createdAt: string | null;
    updatedAt: string | null;
}

/**
 * Simple markdown to HTML converter for print
 */
function simpleMarkdownToHtml(markdown: string): string {
    return markdown
        // Escape HTML
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        // Headers
        .replace(/^## (.+)$/gm, '<h3 class="text-lg font-semibold mt-4 mb-2">$1</h3>')
        .replace(/^### (.+)$/gm, '<h4 class="text-base font-medium mt-3 mb-1">$1</h4>')
        // Bold
        .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
        // Lists - use proper list styling without extra bullets
        .replace(/^- (.+)$/gm, '<div class="ml-4 flex"><span class="mr-2">•</span><span>$1</span></div>')
        .replace(/^(\d+)\. (.+)$/gm, '<div class="ml-4 flex"><span class="mr-2 min-w-[1.5rem]">$1.</span><span>$2</span></div>')
        // Checkboxes
        .replace(/^- \[ \] (.+)$/gm, '<div class="ml-4 flex"><span class="mr-2">☐</span><span>$1</span></div>')
        .replace(/^- \[x\] (.+)$/gm, '<div class="ml-4 flex"><span class="mr-2">☑</span><span>$1</span></div>')
        // Tables (basic)
        .replace(/\|(.+)\|/g, (match, content) => {
            const cells = content.split('|').map((cell: string) => cell.trim());
            if (cells.every((c: string) => c.match(/^-+$/))) {
                return ''; // Skip separator row
            }
            return '<tr>' + cells.map((cell: string) => `<td class="border px-2 py-1">${cell}</td>`).join('') + '</tr>';
        })
        // Line breaks
        .replace(/\n\n/g, '</p><p class="my-2">')
        .replace(/\n/g, '<br/>')
        // Wrap in paragraph
        .replace(/^(.+)$/, '<p class="my-2">$1</p>');
}

export default function DocumentationPage() {
    const [data, setData] = useState<DocumentationData | null>(null);
    const [isLoading, setIsLoading] = useState(true);
    const [isSaving, setIsSaving] = useState(false);
    const [saveSuccess, setSaveSuccess] = useState(false);
    const [error, setError] = useState<string | null>(null);
    const [expandedSections, setExpandedSections] = useState<Set<string>>(new Set(['allgemeine-beschreibung']));

    useEffect(() => {
        loadDocumentation();
    }, []);

    async function loadDocumentation() {
        setIsLoading(true);
        setError(null);
        try {
            const response = await fetch('/api/documentation');
            if (response.ok) {
                const docData = await response.json();
                setData(docData);
            } else {
                setError('Fehler beim Laden der Dokumentation');
            }
        } catch (err) {
            console.error('Error loading documentation:', err);
            setError('Fehler beim Laden der Dokumentation');
        }
        setIsLoading(false);
    }

    async function saveDocumentation() {
        if (!data) return;

        setIsSaving(true);
        setSaveSuccess(false);
        setError(null);

        try {
            const response = await fetch('/api/documentation', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    title: data.title,
                    content: data.content,
                }),
            });

            if (response.ok) {
                const updatedData = await response.json();
                setData(updatedData);
                setSaveSuccess(true);
                setTimeout(() => setSaveSuccess(false), 3000);
            } else {
                setError('Fehler beim Speichern');
            }
        } catch (err) {
            console.error('Error saving documentation:', err);
            setError('Fehler beim Speichern');
        }
        setIsSaving(false);
    }

    function updateCompanyInfo(field: keyof DocumentationContent, value: string) {
        if (!data) return;
        setData({
            ...data,
            content: { ...data.content, [field]: value },
        });
    }

    function updateSectionContent(sectionId: string, content: string) {
        if (!data) return;
        setData({
            ...data,
            content: {
                ...data.content,
                sections: data.content.sections.map(s =>
                    s.id === sectionId ? { ...s, content } : s
                ),
            },
        });
    }

    function toggleSection(sectionId: string) {
        const newExpanded = new Set(expandedSections);
        if (newExpanded.has(sectionId)) {
            newExpanded.delete(sectionId);
        } else {
            newExpanded.add(sectionId);
        }
        setExpandedSections(newExpanded);
    }

    function exportAsPDF() {
        // For now, open print dialog which allows PDF export
        window.print();
    }

    if (isLoading) {
        return (
            <div className="min-h-screen bg-background flex items-center justify-center">
                <div className="text-center">
                    <RefreshCw className="h-8 w-8 animate-spin mx-auto mb-4 text-primary" />
                    <p className="text-muted-foreground">Laden...</p>
                </div>
            </div>
        );
    }

    return (
        <div className="min-h-screen bg-background print:bg-white">
            <div className="max-w-4xl mx-auto px-4 py-8 print:max-w-none print:px-8">
                {/* Back Link - hide in print */}
                <Link
                    href="/settings"
                    className="inline-flex items-center text-sm text-muted-foreground hover:text-foreground mb-6 print:hidden"
                >
                    <ArrowLeft className="h-4 w-4 mr-2" />
                    Zurück zu Einstellungen
                </Link>

                {/* Header */}
                <header className="mb-8">
                    <div className="flex items-start justify-between">
                        <div className="flex items-center gap-3 mb-4">
                            <div className="p-2 bg-primary/10 rounded-lg print:hidden">
                                <Shield className="h-8 w-8 text-primary" />
                            </div>
                            <div>
                                <h1 className="text-3xl font-bold tracking-tight">GoBD Verfahrensdokumentation</h1>
                                <p className="text-muted-foreground">
                                    Dokumentation des Buchführungsverfahrens gemäß GoBD
                                </p>
                            </div>
                        </div>
                        <div className="flex gap-2 print:hidden">
                            <Button variant="outline" onClick={exportAsPDF}>
                                <Download className="h-4 w-4 mr-2" />
                                Drucken/PDF
                            </Button>
                            <Button onClick={saveDocumentation} disabled={isSaving}>
                                {isSaving ? (
                                    <RefreshCw className="h-4 w-4 mr-2 animate-spin" />
                                ) : saveSuccess ? (
                                    <CheckCircle2 className="h-4 w-4 mr-2 text-green-500" />
                                ) : (
                                    <Save className="h-4 w-4 mr-2" />
                                )}
                                {saveSuccess ? 'Gespeichert' : 'Speichern'}
                            </Button>
                        </div>
                    </div>

                    {/* Status Info */}
                    {data && (
                        <div className="flex flex-wrap gap-2 print:hidden">
                            <Badge variant="outline" className="gap-1">
                                <Server className="h-3 w-3" />
                                Version {data.version}
                            </Badge>
                            {data.updatedAt && (
                                <Badge variant="outline" className="gap-1">
                                    Letzte Änderung: {format(new Date(data.updatedAt), 'dd.MM.yyyy HH:mm', { locale: de })}
                                </Badge>
                            )}
                            {data.id ? (
                                <Badge className="bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-400 gap-1">
                                    <CheckCircle2 className="h-3 w-3" />
                                    Gespeichert
                                </Badge>
                            ) : (
                                <Badge className="bg-amber-100 text-amber-700 dark:bg-amber-900/30 dark:text-amber-400 gap-1">
                                    <AlertCircle className="h-3 w-3" />
                                    Noch nicht gespeichert
                                </Badge>
                            )}
                        </div>
                    )}

                    {error && (
                        <div className="mt-4 p-3 bg-red-50 dark:bg-red-950/20 border border-red-200 dark:border-red-800 rounded-lg text-red-700 dark:text-red-400 text-sm print:hidden">
                            {error}
                        </div>
                    )}
                </header>

                {data && (
                    <div className="space-y-6">
                        {/* Company Information Card */}
                        <Card className="print:shadow-none print:border-none">
                            <CardHeader>
                                <CardTitle className="flex items-center gap-2">
                                    <Building2 className="h-5 w-5" />
                                    Unternehmensdaten
                                </CardTitle>
                                <CardDescription>
                                    Grundlegende Informationen zum Unternehmen
                                </CardDescription>
                            </CardHeader>
                            <CardContent className="grid grid-cols-1 md:grid-cols-2 gap-4">
                                <div className="space-y-2">
                                    <Label htmlFor="companyName">Unternehmensname</Label>
                                    <Input
                                        id="companyName"
                                        value={data.content.companyName}
                                        onChange={(e) => updateCompanyInfo('companyName', e.target.value)}
                                        placeholder="Muster GmbH"
                                        className="print:border-none print:px-0"
                                    />
                                </div>
                                <div className="space-y-2">
                                    <Label htmlFor="taxNumber">Steuernummer</Label>
                                    <Input
                                        id="taxNumber"
                                        value={data.content.taxNumber}
                                        onChange={(e) => updateCompanyInfo('taxNumber', e.target.value)}
                                        placeholder="123/456/78901"
                                        className="print:border-none print:px-0"
                                    />
                                </div>
                                <div className="space-y-2 md:col-span-2">
                                    <Label htmlFor="companyAddress">Adresse</Label>
                                    <Input
                                        id="companyAddress"
                                        value={data.content.companyAddress}
                                        onChange={(e) => updateCompanyInfo('companyAddress', e.target.value)}
                                        placeholder="Musterstraße 1, 12345 Musterstadt"
                                        className="print:border-none print:px-0"
                                    />
                                </div>
                                <div className="space-y-2 md:col-span-2">
                                    <Label htmlFor="responsiblePerson">Verantwortliche Person</Label>
                                    <Input
                                        id="responsiblePerson"
                                        value={data.content.responsiblePerson}
                                        onChange={(e) => updateCompanyInfo('responsiblePerson', e.target.value)}
                                        placeholder="Max Mustermann"
                                        className="print:border-none print:px-0"
                                    />
                                </div>
                            </CardContent>
                        </Card>

                        {/* System Info Card */}
                        <Card className="print:shadow-none print:border-none">
                            <CardHeader>
                                <CardTitle className="flex items-center gap-2">
                                    <Server className="h-5 w-5" />
                                    System-Information
                                    <Badge variant="secondary" className="ml-2 text-xs">Auto-generiert</Badge>
                                </CardTitle>
                                <CardDescription>
                                    Automatisch erfasste technische Informationen
                                </CardDescription>
                            </CardHeader>
                            <CardContent>
                                <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-4">
                                    <div className="p-3 bg-muted/50 rounded-lg">
                                        <div className="text-sm text-muted-foreground">Software</div>
                                        <div className="font-medium">{data.content.systemInfo?.softwareName || 'Bivaro'}</div>
                                    </div>
                                    <div className="p-3 bg-muted/50 rounded-lg">
                                        <div className="text-sm text-muted-foreground">Version</div>
                                        <div className="font-medium">{data.content.systemInfo?.softwareVersion || data.version}</div>
                                    </div>
                                    <div className="p-3 bg-muted/50 rounded-lg">
                                        <div className="text-sm text-muted-foreground">Datenbank</div>
                                        <div className="font-medium">{data.content.systemInfo?.databaseType || 'SQLite'}</div>
                                    </div>
                                </div>

                                <div>
                                    <div className="text-sm text-muted-foreground mb-2">Verfügbare Funktionen:</div>
                                    <div className="flex flex-wrap gap-1">
                                        {data.content.systemInfo?.features?.map((feature, idx) => (
                                            <Badge key={idx} variant="outline" className="text-xs">{feature}</Badge>
                                        ))}
                                    </div>
                                </div>
                            </CardContent>
                        </Card>

                        {/* Documentation Sections */}
                        {data.content.sections.map((section) => (
                            <Card key={section.id} className="print:shadow-none print:border-none print:break-inside-avoid">
                                <Collapsible
                                    open={expandedSections.has(section.id)}
                                    onOpenChange={() => toggleSection(section.id)}
                                >
                                    <CollapsibleTrigger asChild>
                                        <CardHeader className="cursor-pointer hover:bg-muted/50 transition-colors print:cursor-default">
                                            <CardTitle className="flex items-center justify-between">
                                                <div className="flex items-center gap-2">
                                                    <FileText className="h-5 w-5" />
                                                    {section.title}
                                                    {section.isAutoGenerated && (
                                                        <Badge variant="secondary" className="ml-2 text-xs print:hidden">Auto-generiert</Badge>
                                                    )}
                                                </div>
                                                <div className="print:hidden">
                                                    {expandedSections.has(section.id) ? (
                                                        <ChevronDown className="h-5 w-5 text-muted-foreground" />
                                                    ) : (
                                                        <ChevronRight className="h-5 w-5 text-muted-foreground" />
                                                    )}
                                                </div>
                                            </CardTitle>
                                            <CardDescription>{section.description}</CardDescription>
                                        </CardHeader>
                                    </CollapsibleTrigger>
                                    <CollapsibleContent className="print:block">
                                        <CardContent>
                                            {section.isAutoGenerated ? (
                                                <div className="prose prose-sm dark:prose-invert max-w-none">
                                                    <div
                                                        className="p-4 bg-muted/30 rounded-lg text-sm print:bg-transparent print:p-0"
                                                        dangerouslySetInnerHTML={{ __html: simpleMarkdownToHtml(section.content) }}
                                                    />
                                                    <p className="text-xs text-muted-foreground mt-2 flex items-center gap-1 print:hidden">
                                                        <Info className="h-3 w-3" />
                                                        Dieser Abschnitt wird automatisch generiert und aktualisiert sich bei Änderungen.
                                                    </p>
                                                </div>
                                            ) : (
                                                <>
                                                    {/* Edit mode - hidden in print */}
                                                    <Textarea
                                                        value={section.content}
                                                        onChange={(e) => updateSectionContent(section.id, e.target.value)}
                                                        className="min-h-[300px] font-mono text-sm print:hidden"
                                                        placeholder="Inhalt für diesen Abschnitt eingeben..."
                                                    />
                                                    {/* Print mode - rendered markdown */}
                                                    <div
                                                        className="hidden print:block text-sm"
                                                        dangerouslySetInnerHTML={{ __html: simpleMarkdownToHtml(section.content) }}
                                                    />
                                                </>
                                            )}
                                        </CardContent>
                                    </CollapsibleContent>
                                </Collapsible>
                            </Card>
                        ))}

                        {/* Footer Info */}
                        <div className="text-center text-sm text-muted-foreground py-4 print:py-8 print:border-t">
                            <p>Erstellt mit {data.content.systemInfo?.softwareName || 'Bivaro Buchhaltung'} v{data.version}</p>
                            <p>Stand: {format(new Date(), 'dd. MMMM yyyy, HH:mm \'Uhr\'', { locale: de })}</p>
                        </div>
                    </div>
                )}
            </div>
        </div>
    );
}
