/**
 * GoBD Verfahrensdokumentation Template Library
 * Provides structure and auto-generation for GoBD-compliant documentation
 * 
 * Basierend auf dem BMF-Schreiben vom 28.11.2019 (GoBD)
 * "Grundsätze zur ordnungsmäßigen Führung und Aufbewahrung von
 * Büchern, Aufzeichnungen und Unterlagen in elektronischer Form
 * sowie zum Datenzugriff"
 */

// Software version from package.json
const APP_VERSION = '0.1.0';
const APP_NAME = 'Bivaro Buchhaltung';

export interface DocumentationSection {
    id: string;
    title: string;
    description: string;
    content: string;
    isAutoGenerated?: boolean;
}

export interface DocumentationData {
    companyName: string;
    companyAddress: string;
    taxNumber: string;
    responsiblePerson: string;
    sections: DocumentationSection[];
    systemInfo: SystemInfo;
    createdAt: string;
    updatedAt: string;
}

export interface SystemInfo {
    softwareName: string;
    softwareVersion: string;
    databaseType: string;
    features: string[];
    lastUpdated: string;
}

/**
 * Get auto-generated system information
 */
export function getSystemInfo(): SystemInfo {
    return {
        softwareName: APP_NAME,
        softwareVersion: APP_VERSION,
        databaseType: 'SQLite',
        features: [
            'Einnahmen-Überschuss-Rechnung (EÜR) gemäß § 4 Abs. 3 EStG',
            'Kassenbuchführung gemäß § 146 AO',
            'Rechnungserstellung gemäß § 14 UStG',
            'Belegverwaltung mit digitaler Archivierung (§ 147 AO)',
            'Kundenverwaltung',
            'Abschreibungen (AfA) gemäß § 7 EStG',
            'GWG-Verzeichnis (§ 6 Abs. 2 EStG)',
            'Wiederkehrende Ausgaben',
            'Mahnwesen',
            'Unveränderliches Audit-Log (§ 146 Abs. 4 AO)',
            'Datensicherung und Backup',
            'API-Zugang für externe Systeme',
        ],
        lastUpdated: new Date().toISOString(),
    };
}

/**
 * Get the default GoBD documentation template
 * Vollständige Verfahrensdokumentation gemäß BMF-Schreiben GoBD Rz. 151-155
 */
export function getDefaultDocumentationTemplate(): DocumentationSection[] {
    const systemInfo = getSystemInfo();

    return [
        {
            id: 'allgemeine-beschreibung',
            title: '1. Allgemeine Beschreibung',
            description: 'Organisatorische und rechtliche Grundlagen gemäß GoBD Rz. 151',
            content: `## 1.1 Eingesetzte Software

**Programmname:** ${systemInfo.softwareName}
**Version:** ${systemInfo.softwareVersion}
**Datenbank:** ${systemInfo.databaseType}
**Hersteller:** Eigenentwicklung / Open Source

## 1.2 Anwendungsbereich

Die Software dient der ordnungsgemäßen Buchführung für:
- Kleinunternehmer gemäß § 19 UStG
- Gewerbetreibende mit Einnahmen-Überschuss-Rechnung (§ 4 Abs. 3 EStG)
- Freiberufler

## 1.3 Rechtliche Grundlagen

Die Verfahrensdokumentation erfüllt die Anforderungen aus:
- § 145 AO (Allgemeine Anforderungen an Buchführung und Aufzeichnungen)
- § 146 AO (Ordnungsvorschriften für die Buchführung und für Aufzeichnungen)
- § 147 AO (Ordnungsvorschriften für die Aufbewahrung von Unterlagen)
- BMF-Schreiben vom 28.11.2019 (GoBD)

## 1.4 Verfügbare Funktionen

${systemInfo.features.map(f => `- ${f}`).join('\n')}

## 1.5 Grundsätze ordnungsgemäßer Buchführung

Das System gewährleistet:
- **Nachvollziehbarkeit und Nachprüfbarkeit** (§ 145 Abs. 1 AO)
- **Vollständigkeit** aller Geschäftsvorfälle
- **Richtigkeit** der Erfassung
- **Zeitgerechte Buchung** und Aufzeichnung
- **Ordnung** durch systematische Erfassung
- **Unveränderbarkeit** durch Audit-Log`,
            isAutoGenerated: true,
        },
        {
            id: 'anwenderdokumentation',
            title: '2. Anwenderdokumentation',
            description: 'Bedienungsanleitung gemäß GoBD Rz. 152',
            content: `## 2.1 Benutzerrollen und Berechtigungen

| Rolle | Berechtigungen |
|-------|----------------|
| Administrator | Vollzugriff inkl. Benutzerverwaltung, Backup, Einstellungen |
| Benutzer | Erfassung von Einnahmen, Ausgaben, Rechnungen; Keine Admin-Rechte |

## 2.2 Anmeldung und Authentifizierung

- Zugang erfolgt über persönliche Benutzerkonten (E-Mail + Passwort)
- Passwörter werden verschlüsselt gespeichert (bcrypt)
- Jede An- und Abmeldung wird im Audit-Log protokolliert

## 2.3 Erfassung von Geschäftsvorfällen

### Einnahmen erfassen
1. Navigation zu "Dashboard" → Tab "Einnahmen"
2. Eingabe: Datum, Beschreibung, Betrag, Kategorie
3. Optional: Kunde auswählen oder neu anlegen
4. Optional: Beleg hochladen
5. Speichern mit "Einnahme hinzufügen"

### Ausgaben erfassen
1. Navigation zu "Dashboard" → Tab "Ausgaben"
2. Eingabe: Datum, Beschreibung, Betrag, Kategorie
3. Optional: Beleg hochladen (PDF, JPG, PNG - max. 10 MB)
4. EÜR-Zeile wird automatisch vorgeschlagen
5. Speichern mit "Ausgabe hinzufügen"

### Kassenbuchführung (§ 146 AO)
1. Navigation zu "Kassenbuch"
2. Tägliche Erfassung aller Bargeschäfte
3. Jede Bewegung mit Datum, Beleg-Nr., Beschreibung, Betrag
4. Täglicher Kassenabschluss mit Soll-Ist-Vergleich
5. Keine nachträgliche Änderung möglich (Stornobuchung erforderlich)

### Rechnungserstellung (§ 14 UStG)
1. Navigation zu "Dashboard" → Tab "Rechnungen"
2. Kunde auswählen oder neu anlegen
3. Positionen eingeben (Beschreibung, Menge, Einzelpreis)
4. Rechnungsnummer wird automatisch fortlaufend vergeben
5. PDF-Erstellung und Versand

## 2.4 Korrektur von Buchungen

Gemäß § 146 Abs. 4 AO dürfen Aufzeichnungen nicht nachträglich geändert werden.
Das System erzwingt:
- **Stornobuchung** statt Löschung
- **Automatisches Audit-Log** aller Änderungen
- **Sichtbarer Änderungsverlauf** unter Einstellungen → Audit-Log

## 2.5 Belegablage und Archivierung

- Belege werden im Originalformat gespeichert (keine Konvertierung)
- Speicherort: /data/uploads (verschlüsselter Ordner)
- Zugriff nur für authentifizierte Benutzer
- Aufbewahrung gemäß § 147 AO (10 Jahre)`,
            isAutoGenerated: false,
        },
        {
            id: 'technische-dokumentation',
            title: '3. Technische Systemdokumentation',
            description: 'Hardware, Software und Schnittstellen gemäß GoBD Rz. 153',
            content: `## 3.1 Systemarchitektur

**Anwendungstyp:** Webbasierte Anwendung (Self-Hosted)
**Framework:** Next.js (React)
**Datenbank:** ${systemInfo.databaseType} (lokale Datei)
**Verschlüsselung:** HTTPS/TLS für Netzwerkzugriff

## 3.2 Datenspeicherung und -struktur

### Datenbankschema
- Relationale Datenbank mit referentieller Integrität
- Automatische Zeitstempel (createdAt, updatedAt)
- Fremdschlüsselbeziehungen für Datenkonsistenz

### Speicherorte
- **Datenbank:** /prisma/dev.db
- **Belege/Dokumente:** /data/uploads/
- **Backups:** Manueller Export über Einstellungen

## 3.3 Unveränderbarkeit (§ 146 Abs. 4 AO)

Das System gewährleistet Unveränderbarkeit durch:

1. **Audit-Log-Tabelle:** Jede Datenänderung wird protokolliert mit:
   - Zeitstempel (createdAt)
   - Benutzer-ID
   - Aktion (CREATE, UPDATE, DELETE)
   - Betroffene Entität und ID
   - Alte und neue Werte (JSON)
   - IP-Adresse

2. **Keine physische Löschung:** Gelöschte Datensätze werden markiert, nicht entfernt

3. **Zeitstempelbasierte Versionierung:** Jede Änderung erhält neuen Zeitstempel

## 3.4 Datensicherung (§ 147 Abs. 6 AO)

### Backup-Funktionen
- **JSON-Backup:** Export aller Daten als JSON-Datei
- **ZIP-Backup:** Vollständiges Backup inkl. Dateien
- **Wiederherstellung:** Import über Einstellungen → Datensicherung

### Empfohlene Backup-Strategie
- Täglich: Inkrementelles Backup
- Wöchentlich: Vollständiges Backup
- Monatlich: Externes Backup (offsite)

## 3.5 Schnittstellen

### REST API
- Authentifizierung: API-Key (Bearer Token)
- Dokumentation: /settings/api-keys/docs
- Endpunkte für: Kunden, Ausgaben, Einnahmen, Rechnungen

### Elster Export
- CSV-Export für EÜR-Formulare
- Zuordnung zu offiziellen EÜR-Zeilen (Anlage EÜR)

## 3.6 Datenzugriff (§ 147 Abs. 6 AO)

Für Betriebsprüfungen stehen folgende Zugriffsmöglichkeiten bereit:
- **Z1 (Unmittelbarer Zugriff):** Lesezugriff über Benutzeroberfläche
- **Z2 (Mittelbarer Zugriff):** Export über API oder Backup-Funktion
- **Z3 (Datenträgerüberlassung):** Vollständiges ZIP-Backup`,
            isAutoGenerated: true,
        },
        {
            id: 'betriebsdokumentation',
            title: '4. Betriebsdokumentation',
            description: 'IKS, Prozesse und Verantwortlichkeiten gemäß GoBD Rz. 154',
            content: `## 4.1 Organisationsstruktur

| Funktion | Name | Vertretung |
|----------|------|------------|
| Systemadministration | [Name eintragen] | [Name eintragen] |
| Datensicherung | [Name eintragen] | [Name eintragen] |
| Buchführung | [Name eintragen] | [Name eintragen] |
| Belegprüfung | [Name eintragen] | [Name eintragen] |

## 4.2 Internes Kontrollsystem (IKS)

### Zugriffskontrollen
- Persönliche Benutzerkonten (keine Sammelkonten)
- Rollenbasierte Berechtigungen (Admin/Benutzer)
- Automatische Abmeldung nach Inaktivität
- Protokollierung aller Zugriffsversuche

### Eingabekontrollen
- Pflichtfeldvalidierung bei Erfassung
- Formatprüfung (Datum, Beträge, IBAN)
- Plausibilitätsprüfungen (z.B. keine negativen Einnahmen)
- Warnhinweise bei ungewöhnlichen Beträgen

### Verarbeitungskontrollen
- Automatische Berechnung von Summen
- Keine manuelle Manipulation von Berechnungen
- Prüfsummen für exportierte Daten

## 4.3 Regelmäßige Prozesse

### Tägliche Aufgaben
- [ ] Erfassung aller Bargeschäfte im Kassenbuch
- [ ] Prüfung Kassenbestand (Soll-Ist-Vergleich)
- [ ] Ablage eingehender Belege

### Wöchentliche Aufgaben
- [ ] Bankabgleich mit Kontoauszügen
- [ ] Prüfung offener Rechnungen
- [ ] Backup erstellen

### Monatliche Aufgaben
- [ ] Kontrolle der Einnahmen und Ausgaben
- [ ] Mahnlauf für überfällige Rechnungen
- [ ] UStVA-Vorbereitung (falls erforderlich)

### Jährliche Aufgaben
- [ ] EÜR-Erstellung für das Finanzamt
- [ ] Inventur und Bestandsaufnahme
- [ ] Archivierung des Jahresdatensatzes
- [ ] Prüfung und Aktualisierung dieser Verfahrensdokumentation
- [ ] Prüfung der Aufbewahrungsfristen

## 4.4 Aufbewahrungsfristen (§ 147 AO)

| Dokumentenart | Frist | Beginn |
|---------------|-------|--------|
| Handelsbücher, Inventare, Bilanzen | 10 Jahre | Ende des Kalenderjahres |
| Buchungsbelege | 10 Jahre | Ende des Kalenderjahres |
| Empfangene Handels- und Geschäftsbriefe | 6 Jahre | Ende des Kalenderjahres |
| Wiedergaben abgesandter Handels- und Geschäftsbriefe | 6 Jahre | Ende des Kalenderjahres |
| Sonstige Unterlagen | 6 Jahre | Ende des Kalenderjahres |

## 4.5 Verfahren bei Systemausfällen

1. **Sofortmaßnahmen:**
   - Manuelle Erfassung auf Papier
   - Dokumentation des Ausfallzeitraums

2. **Wiederherstellung:**
   - Restore aus letztem Backup
   - Nacherfassung der manuellen Aufzeichnungen
   - Protokollierung der Wiederherstellung

3. **Nachbereitung:**
   - Ursachenanalyse
   - Maßnahmen zur Vermeidung dokumentieren`,
            isAutoGenerated: false,
        },
        {
            id: 'aenderungsprotokoll',
            title: '5. Änderungsprotokoll',
            description: 'Versionierung der Verfahrensdokumentation gemäß GoBD Rz. 155',
            content: `## 5.1 Versionsverlauf

| Version | Datum | Änderung | Verantwortlich |
|---------|-------|----------|----------------|
| 1.0 | [Datum] | Erstfassung | [Name] |
| | | | |
| | | | |

## 5.2 Änderungsgrund

Bei jeder Änderung der Verfahrensdokumentation ist zu dokumentieren:
- Was wurde geändert?
- Warum wurde es geändert?
- Wer hat die Änderung veranlasst?
- Wer hat die Änderung genehmigt?

## 5.3 Aufbewahrung alter Versionen

Alle Versionen dieser Verfahrensdokumentation sind für die Dauer der Aufbewahrungsfristen (§ 147 AO) aufzubewahren. Die Aufbewahrung erfolgt:
- Digital im System (automatisch versioniert)
- Optional: Ausdruck in Papierform

## 5.4 Gültigkeit

Diese Verfahrensdokumentation tritt mit Datum der Erstfassung in Kraft und ist gültig bis zur nächsten Aktualisierung.

**Unterschrift Geschäftsführung:**

_____________________________
Ort, Datum

_____________________________
Unterschrift, Name`,
            isAutoGenerated: false,
        },
    ];
}

/**
 * Create empty documentation data with defaults
 */
export function createEmptyDocumentation(): Omit<DocumentationData, 'createdAt' | 'updatedAt'> {
    return {
        companyName: '',
        companyAddress: '',
        taxNumber: '',
        responsiblePerson: '',
        sections: getDefaultDocumentationTemplate(),
        systemInfo: getSystemInfo(),
    };
}

/**
 * Get current app version
 */
export function getAppVersion(): string {
    return APP_VERSION;
}
