import packageJson from '@/package.json';

/**
 * GoBD Verfahrensdokumentation Template Library
 * Provides structure and auto-generation for a reviewable documentation draft.
 * 
 * Basierend auf dem BMF-Schreiben vom 28.11.2019 (GoBD)
 * "Grundsätze zur ordnungsmäßigen Führung und Aufbewahrung von
 * Büchern, Aufzeichnungen und Unterlagen in elektronischer Form
 * sowie zum Datenzugriff"
 */

// Keep the generated documentation tied to the release metadata shipped with the app.
const APP_VERSION = packageJson.version;
const APP_NAME = 'Bivaro Buchhaltung';

export interface DocumentationSection {
    id: string;
    title: string;
    description: string;
    content: string;
    isAutoGenerated?: boolean;
}

export interface DocumentationData {
    companyName: string;
    companyAddress: string;
    taxNumber: string;
    responsiblePerson: string;
    sections: DocumentationSection[];
    systemInfo: SystemInfo;
    createdAt: string;
    updatedAt: string;
}

export interface SystemInfo {
    softwareName: string;
    softwareVersion: string;
    databaseType: string;
    features: string[];
    operatorTasks: string[];
    knownLimitations: string[];
    lastUpdated: string;
}

/**
 * Get auto-generated system information
 */
export function getSystemInfo(): SystemInfo {
    return {
        softwareName: APP_NAME,
        softwareVersion: APP_VERSION,
        databaseType: 'SQLite',
        features: [
            'Einnahmen-Überschuss-Rechnung (EÜR)',
            'Kassenbücher mit laufender Saldenberechnung',
            'Rechnungserstellung und Status-/Zahlungserfassung',
            'Belegverwaltung mit mandantenbezogenem, privatem Upload-Speicher',
            'Kundenverwaltung',
            'Abschreibungen (AfA)',
            'GWG-Verzeichnis',
            'Wiederkehrende Ausgaben',
            'Mahnwesen',
            'Transaktionales Finanz-Audit für ausgewählte Rechnungs- und Zahlungspfade; übrige Mutationen und Security-Telemetrie best effort',
            'Backup v3 mit Manifest, Auditsegment und Rechnungsnummern-High-Water-Mark; v2 als Legacy-Format',
            'API-Zugang für externe Systeme',
        ],
        operatorTasks: [
            'HTTPS/TLS am Reverse Proxy oder am Host einrichten und regelmäßig prüfen; die Anwendung weist diese Konfiguration nicht nach.',
            'Verschlüsselung des Hosts und des Datenträgers für Datenbank, Uploads und Backups einrichten; eine Anwendungsverschlüsselung ist nicht vorhanden.',
            'Backups regelmäßig, getrennt und wiederherstellbar ausführen und die Ergebnisse dokumentieren; automatische Backup-Zeitpläne sind nicht Teil der Anwendung.',
            'Verantwortliche Person, Vertretung, Freigabe und fachliche Aufbewahrungsregeln eintragen und regelmäßig prüfen.',
        ],
        knownLimitations: [
            'Fachliche Datensätze und Kassenbuchungen können über autorisierte Wege geändert oder gelöscht werden. Ein unveränderlicher Datenbestand oder ein allgemeiner Stornozwang ist nicht nachgewiesen.',
            'Das Finanz-Audit ist nur für ausgewählte Rechnungs-, Zahlungs- und Stornopfade transaktional verpflichtend. Andere Mutationen sowie Security-Telemetrie bleiben best effort; eine vollständige Ereignisabdeckung ist offen.',
            'Backup v3 weist Modellabdeckung, ein append-only Auditsegment, Rechnungsnummern-High-Water-Marks und bei ZIP-Dateien Dateihashes aus. Das belegt keine vollständige Original- oder Dateiabdeckung; v2 bleibt ohne diese Nachweise.',
            'Die Anwendung prüft weder Hostverschlüsselung noch eine vollständige GoBD-Abdeckung. Diese Punkte bleiben offene Betreiber- beziehungsweise Reviewaufgaben.',
            'Die Weboberfläche aktualisiert den bestehenden Dokumentdatensatz. Eine dauerhafte, unveränderliche Freigabehistorie ist für diesen Workflow nicht eingerichtet.',
        ],
        lastUpdated: new Date().toISOString(),
    };
}

/**
 * Get the default GoBD documentation template
 * Entwurf zur betrieblichen Ergänzung und Prüfung, keine vollständige Abnahme.
 */
export function getDefaultDocumentationTemplate(): DocumentationSection[] {
    const systemInfo = getSystemInfo();

    return [
        {
            id: 'allgemeine-beschreibung',
            title: '1. Allgemeine Beschreibung',
            description: 'Organisatorische und rechtliche Grundlagen gemäß GoBD Rz. 151',
            content: `## 1.1 Eingesetzte Software

**Programmname:** ${systemInfo.softwareName}
**Version:** ${systemInfo.softwareVersion}
**Datenbank:** ${systemInfo.databaseType}
**Hersteller:** Eigenentwicklung / Open Source

## 1.2 Anwendungsbereich

Die Software kann grundsätzlich für folgende Betriebstypen geprüft werden; eine
fachliche Eignung oder rechtliche Freigabe ist damit nicht zugesagt:
- Kleinunternehmer gemäß § 19 UStG
- Gewerbetreibende mit Einnahmen-Überschuss-Rechnung (§ 4 Abs. 3 EStG)
- Freiberufler

## 1.3 Geltungsstatus und fachliche Prüfung

Diese automatisch erzeugte Systembeschreibung ist ein technischer Entwurf. Sie ist
kein Zertifikat, keine rechtliche Freigabe und kein Nachweis einer vollständigen
GoBD-Abdeckung. Die folgenden Rechtsquellen dienen als Prüf- und Abstimmungsgrundlage:
- § 145 AO (Allgemeine Anforderungen an Buchführung und Aufzeichnungen)
- § 146 AO (Ordnungsvorschriften für die Buchführung und für Aufzeichnungen)
- § 147 AO (Ordnungsvorschriften für die Aufbewahrung von Unterlagen)
- BMF-Schreiben vom 28.11.2019 (GoBD), einschließlich der Änderungen vom 11.03.2024 und 14.07.2025

Die verantwortliche Person muss den betrieblichen Ablauf, die Aufbewahrung, die
Freigabe und die offenen Betreiberaufgaben fachlich prüfen und ergänzen.

## 1.4 Im Code erkennbare Funktionen

${systemInfo.features.map(f => `- ${f}`).join('\n')}

## 1.5 Betreiberaufgaben und offene Abweichungen

### Betreiberaufgaben

${systemInfo.operatorTasks.map(task => `- [ ] ${task}`).join('\n')}

### Bekannte Abweichungen und Grenzen

${systemInfo.knownLimitations.map(limitation => `- ${limitation}`).join('\n')}

## 1.6 Nachgewiesene technische Kontrollen

Die folgenden Kontrollen sind im aktuellen Code erkennbar; ihre fachliche Eignung
und Vollständigkeit sind durch die verantwortliche Person zu bestätigen:
- Server prüft Benutzer-/Mandantenbezug an den betroffenen Datenzugriffen.
- Ausgewählte Rechnungs-, Zahlungs- und Stornopfade schreiben ihr Finanz-Audit in derselben Datenbanktransaktion; andere Mutationen rufen das Audit-Log best effort auf.
- Uploads werden unter servergenerierten Namen außerhalb von public/ in einem mandantenbezogenen Verzeichnis gespeichert.
- Passwörter werden als bcrypt-Hash gespeichert; das ist keine reversible Verschlüsselung.
- Backup- und Restore-Pfade validieren Struktur und Dateireferenzen.

Ein technischer Nachweis für Unveränderbarkeit, Verschlüsselung at rest oder eine
vollständige Verfahrensabdeckung ist damit nicht verbunden.`,
            isAutoGenerated: true,
        },
        {
            id: 'anwenderdokumentation',
            title: '2. Anwenderdokumentation',
            description: 'Bedienungsanleitung gemäß GoBD Rz. 152',
            content: `## 2.1 Benutzerrollen und Berechtigungen

| Rolle | Berechtigungen |
|-------|----------------|
| Administrator | Vollzugriff inkl. Benutzerverwaltung, Backup, Einstellungen |
| Benutzer | Erfassung von Einnahmen, Ausgaben, Rechnungen; Keine Admin-Rechte |

## 2.2 Anmeldung und Authentifizierung

- Zugang erfolgt über persönliche Benutzerkonten (E-Mail + Passwort)
- Passwörter werden als bcrypt-Hash gespeichert (keine reversible Verschlüsselung)
- Sicherheits- und Mutationsereignisse werden an ausgewählten Stellen im Audit-Log erfasst. Für die ausgewählten Rechnungs- und Zahlungspfade ist das Finanz-Audit transaktional; eine vollständige Ereignisabdeckung ist nicht zugesagt.

## 2.3 Erfassung von Geschäftsvorfällen

### Einnahmen erfassen
1. Navigation zu "Dashboard" → Tab "Einnahmen"
2. Eingabe: Datum, Beschreibung, Betrag, Kategorie
3. Optional: Kunde auswählen oder neu anlegen
4. Optional: Beleg hochladen
5. Speichern mit "Einnahme hinzufügen"

### Ausgaben erfassen
1. Navigation zu "Dashboard" → Tab "Ausgaben"
2. Eingabe: Datum, Beschreibung, Betrag, Kategorie
3. Optional: Beleg hochladen (PDF, JPG, PNG - max. 10 MB)
4. EÜR-Zeile wird automatisch vorgeschlagen
5. Speichern mit "Ausgabe hinzufügen"

### Kassenbuchführung (§ 146 AO)
1. Navigation zu "Kassenbuch"
2. Tägliche Erfassung aller Bargeschäfte
3. Jede Bewegung mit Datum, Beleg-Nr., Beschreibung, Betrag
4. Täglicher Kassenabschluss mit Soll-Ist-Vergleich
5. Änderungen und Löschungen sind über autorisierte Wege möglich und müssen betrieblich kontrolliert sowie nachvollziehbar dokumentiert werden

### Rechnungserstellung (§ 14 UStG)
1. Navigation zu "Dashboard" → Tab "Rechnungen"
2. Kunde auswählen oder neu anlegen
3. Positionen eingeben (Beschreibung, Menge, Einzelpreis)
4. Rechnungsnummer wird automatisch fortlaufend vergeben
5. PDF-Erstellung und Versand

## 2.4 Korrektur von Buchungen

Gemäß § 146 Abs. 4 AO muss bei Änderungen der ursprüngliche Inhalt feststellbar
bleiben; auch die zeitliche Einordnung der Eintragung muss nachvollziehbar sein.
Die Anwendung erzwingt dies nicht allgemein: Fachmutationen können je nach
Entität geändert oder gelöscht werden. Für ausgewählte Rechnungs-, Zahlungs- und
Stornopfade wird der Finanz-Audit-Eintrag in derselben Transaktion geschrieben;
ein Fehler rollt diese Fachmutation zurück. Andere Audit-Einträge werden
nachgelagert und best effort geschrieben. Der Audit-Log unter Einstellungen
unterstützt die Prüfung, ersetzt aber keine fachliche Freigabe.

## 2.5 Belegablage und Archivierung

- Bei direktem Upload wird der empfangene Inhalt gespeichert; PDF/A-3- und XML-Pfade erzeugen daneben abgeleitete Dokumente. Ein allgemeiner Originalerhalt über alle Konvertierungspfade ist nicht nachgewiesen.
- Speicherort: data/uploads unterhalb des konfigurierten Arbeitsverzeichnisses, außerhalb von public/, mandantenbezogen
- Zugriff über authentifizierte, besitzgeprüfte Routen; Host- und Datenträgerverschlüsselung ist Betreiberaufgabe
- Aufbewahrungsfristen und Lösch-/Hold-Regeln müssen vom Betreiber festgelegt und geprüft werden`,
            isAutoGenerated: false,
        },
        {
            id: 'technische-dokumentation',
            title: '3. Technische Systemdokumentation',
            description: 'Hardware, Software und Schnittstellen gemäß GoBD Rz. 153',
            content: `## 3.1 Systemarchitektur

**Anwendungstyp:** Webbasierte Anwendung (Self-Hosted)
**Framework:** Next.js (React)
**Datenbank:** ${systemInfo.databaseType} (lokale Datei)
**Netzwerkschutz:** HTTPS/TLS muss am Reverse Proxy oder am Host konfiguriert und geprüft werden; die Anwendung weist diese Einstellung nicht nach.
**Verschlüsselung at rest:** Keine anwendungsseitige Verschlüsselung der Datenbank oder Uploads nachgewiesen; Host-/Datenträgerverschlüsselung bleibt Betreiberaufgabe.

## 3.2 Datenspeicherung und -struktur

### Datenbankschema
- Relationale Datenbank mit referentieller Integrität
- Automatische Zeitstempel (createdAt, updatedAt)
- Fremdschlüsselbeziehungen für Datenkonsistenz

### Speicherorte
- **Datenbank:** DATABASE_URL; die Entwicklungs-Voreinstellung ist prisma/dev.db
- **Belege/Dokumente:** data/uploads unterhalb des Arbeitsverzeichnisses, außerhalb von public/, mit mandantenbezogenen Verzeichnissen
- **Backups:** JSON- und ZIP-Export über die Backup-Funktionen; die Ablage, Trennung und Prüfung der Sicherungen ist Betreiberaufgabe

## 3.3 Änderungs- und Löschbarkeit (offene Abweichung)

Die Anwendung bietet technische Kontrollen, stellt aber keine allgemeine
Unveränderbarkeit her:

1. **Audit-Log-Tabelle:** Ausgewählte Rechnungs-, Zahlungs- und Stornopfade lösen in derselben Transaktion einen Eintrag aus; andere Datenänderungen lösen nach der Fachmutation einen best-effort Eintrag aus mit:
   - Zeitstempel (createdAt)
   - Benutzer-ID
   - Aktion (CREATE, UPDATE, DELETE)
   - Betroffene Entität und ID
   - Alte und neue Werte (JSON)
   - IP-Adresse

   Bei den ausgewählten Finanzpfaden rollt ein Audit-Fehler die Fachmutation zurück.
   Bei anderen Pfaden bleibt das Schreiben best effort. Eine vollständige
   Abdeckung und Unverlierbarkeit sind offen.

2. **Fachliche Änderungen:** Rechnungsstatus, Stammdaten und Kassenbuchungen
   können über autorisierte Routen geändert werden. Datensätze können je nach
   Entität physisch gelöscht werden. Ein allgemeiner Stornozwang ist nicht
   implementiert.

3. **Betreiberkontrolle:** Freigabe, Aufbewahrung, Hold und regelmäßige Prüfung
   müssen außerhalb der Anwendung organisiert und belegt werden.

4. **Zugang deaktivieren:** Die Benutzerverwaltung sperrt Anmeldung und
   API-Schlüssel, statt das Benutzerkonto physisch zu löschen. Belege,
   Buchungen und vorhandene Audit-Referenzen bleiben erhalten. Die Sperrung
   und ihr Protokolleintrag werden gemeinsam gespeichert. Eine geregelte
   Datenübernahme durch einen Nachfolger, Reaktivierung und eine endgültige
   Löschung nach Aufbewahrungsprüfung sind noch nicht implementiert.

## 3.4 Datensicherung (§ 147 Abs. 6 AO)

### Backup-Funktionen
- **JSON-Backup v3:** Mandantenbezogener Export der ausgewiesenen Modellabdeckung mit Manifest, Hashes, Auditsegment und Rechnungsnummern-High-Water-Marks. Geheimnisse werden ausgeschlossen; API-Schlüssel müssen nach dem Restore neu ausgestellt werden. Das ist keine Zusage vollständiger fachlicher oder historischer Abdeckung.
- **ZIP-Backup v3:** JSON-v3-Metadaten mit Dateimanifest und Hashes sowie referenzierte Rechnungs-, Beleg- und Logodateien, soweit sie zugreifbar sind. Fehlende Referenzen führen zu einem sichtbaren Fehler; Originalerhalt über alle Konvertierungspfade ist nicht nachgewiesen.
- **Legacy-Backup v2:** Unterstütztes Altformat ohne v3-Manifest, Auditsegment und Rechnungsnummern-High-Water-Mark; Vollständigkeit muss vor einer Nutzung separat geprüft werden.
- **Wiederherstellung:** Import über Einstellungen → Datensicherung

### Betreiberaufgaben für Backups
- Sicherungsrhythmus, Aufbewahrung und getrennten Speicherort festlegen
- Wiederherstellung regelmäßig mit synthetischen oder freigegebenen Daten prüfen
- Zugriff auf Backups begrenzen und Verschlüsselung des Zielsystems nachweisen

## 3.5 Schnittstellen

### REST API
- Authentifizierung: API-Key (Bearer Token)
- Dokumentation: /settings/api-keys/docs
- Endpunkte für: Kunden, Ausgaben, Einnahmen, Rechnungen

### EÜR-Arbeitsblatt
- CSV-/JSON-Auswertung zur fachlichen Prüfung und manuellen Übertragung
- Die unterstützten Formularjahre und Zuordnungen werden beim Export ausgewiesen
- Kein nachgewiesener Direktimport und keine elektronische Übermittlung an ELSTER

## 3.6 Datenzugriff (§ 147 Abs. 6 AO)

Die Anwendung stellt folgende technische Zugriffswege bereit; die Einordnung als
Z1/Z2/Z3 und deren fachliche Eignung muss qualifiziert geprüft werden:
- Lesezugriff über die Benutzeroberfläche
- Export über API oder Backup-Funktion
- JSON-/ZIP-Backup v3 mit ausgewiesener Modellabdeckung und Audit-/Countersegmenten; ZIP-Dateien enthalten referenzierte Dateien und Hashes, soweit diese zugreifbar sind

Ein Betriebsprüfungszugang, eine vollständige Datenabdeckung oder eine
unveränderte Datenträgerüberlassung wird damit nicht zugesagt.`,
            isAutoGenerated: true,
        },
        {
            id: 'betriebsdokumentation',
            title: '4. Betriebsdokumentation',
            description: 'IKS, Prozesse und Verantwortlichkeiten gemäß GoBD Rz. 154',
            content: `## 4.1 Organisationsstruktur

| Funktion | Name | Vertretung |
|----------|------|------------|
| Systemadministration | [Name eintragen] | [Name eintragen] |
| Datensicherung | [Name eintragen] | [Name eintragen] |
| Buchführung | [Name eintragen] | [Name eintragen] |
| Belegprüfung | [Name eintragen] | [Name eintragen] |

## 4.2 Internes Kontrollsystem (IKS)

### Zugriffskontrollen
- Persönliche Benutzerkonten (keine Sammelkonten)
- Rollenbasierte Berechtigungen (Admin/Benutzer)
- Server prüft Session, Benutzer- und Mandantenbezug an geschützten Routen
- TLS-Konfiguration, Kontosperren und weitere Host-/Betriebsmaßnahmen sind zu prüfen

### Eingabekontrollen
- Pflichtfeldvalidierung bei Erfassung
- Formatprüfung (Datum, Beträge, IBAN)
- Fachspezifische Plausibilitätsprüfungen sind je Route unterschiedlich und nicht als vollständige Abdeckung nachgewiesen
- Ungewöhnliche Beträge und Belegvollständigkeit müssen betrieblich geprüft werden

### Verarbeitungskontrollen
- Automatische Berechnung von Summen
- Transaktionen schützen ausgewählte mehrschrittige Mutationen vor Teilzuständen
- Audit-Log-Aufrufe dokumentieren ausgewählte Mutationen best effort
- Unveränderbarkeit und Prüfsummen für Exporte sind nicht allgemein nachgewiesen

## 4.3 Regelmäßige Prozesse

### Tägliche Aufgaben
- [ ] Erfassung aller Bargeschäfte im Kassenbuch
- [ ] Prüfung Kassenbestand (Soll-Ist-Vergleich)
- [ ] Ablage eingehender Belege

### Wöchentliche Aufgaben
- [ ] Bankabgleich mit Kontoauszügen
- [ ] Prüfung offener Rechnungen
- [ ] Backup erstellen

### Monatliche Aufgaben
- [ ] Kontrolle der Einnahmen und Ausgaben
- [ ] Mahnlauf für überfällige Rechnungen
- [ ] UStVA-Vorbereitung (falls erforderlich)

### Jährliche Aufgaben
- [ ] EÜR-Erstellung für das Finanzamt
- [ ] Inventur und Bestandsaufnahme
- [ ] Archivierung des Jahresdatensatzes
- [ ] Prüfung und Aktualisierung dieser Verfahrensdokumentation
- [ ] Prüfung der Aufbewahrungsfristen

## 4.4 Aufbewahrung und Fristen (fachlich zu prüfen)

| Dokumentenart | Betriebliche Frist eintragen | Beginn festlegen |
|---------------|-------|--------|
| Handelsbücher, Inventare, Bilanzen | [fachlich prüfen] | [fachlich prüfen] |
| Buchungsbelege | [fachlich prüfen] | [fachlich prüfen] |
| Empfangene Handels- und Geschäftsbriefe | [fachlich prüfen] | [fachlich prüfen] |
| Wiedergaben abgesandter Handels- und Geschäftsbriefe | [fachlich prüfen] | [fachlich prüfen] |
| Sonstige Unterlagen | [fachlich prüfen] | [fachlich prüfen] |

Die Anwendung erzwingt diese Fristen nicht automatisch. Aufbewahrung, Holds,
Löschfreigaben und ein datensparsamer Nachweis sind als Betreiberprozess zu
definieren und qualifiziert freizugeben.

## 4.5 Verfahren bei Systemausfällen

1. **Sofortmaßnahmen:**
   - Manuelle Erfassung auf Papier
   - Dokumentation des Ausfallzeitraums

2. **Wiederherstellung:**
   - Restore aus letztem Backup
   - Nacherfassung der manuellen Aufzeichnungen
   - Protokollierung der Wiederherstellung

3. **Nachbereitung:**
   - Ursachenanalyse
   - Maßnahmen zur Vermeidung dokumentieren`,
            isAutoGenerated: false,
        },
        {
            id: 'aenderungsprotokoll',
            title: '5. Änderungsprotokoll',
            description: 'Versionierung der Verfahrensdokumentation gemäß GoBD Rz. 155',
            content: `## 5.1 Versionsverlauf

| Version | Datum | Änderung | Verantwortlich |
|---------|-------|----------|----------------|
| ${systemInfo.softwareVersion} | ${systemInfo.lastUpdated} | Automatisch erzeugter technischer Entwurf; fachliche Freigabe offen | [verantwortliche Person eintragen] |
| | | | |
| | | | |

## 5.2 Änderungsgrund

Bei jeder Änderung der Verfahrensdokumentation ist zu dokumentieren:
- Was wurde geändert?
- Warum wurde es geändert?
- Wer hat die Änderung veranlasst?
- Wer hat die Änderung genehmigt?

## 5.3 Aufbewahrung alter Versionen

Die Aufbewahrung und die Dauer sind fachlich festzulegen. Der aktuelle Web-
Workflow aktualisiert den bestehenden Dokumentdatensatz; eine dauerhafte,
unveränderliche Freigabehistorie wird dabei nicht automatisch angelegt. Alte
freigegebene Fassungen müssen vor einer Änderung außerhalb dieses Workflows
gesichert und nachvollziehbar referenziert werden.

## 5.4 Gültigkeit

**Stand des technischen Entwurfs:** ${systemInfo.lastUpdated}

**Gültigkeit und Freigabedatum:** [fachlich festlegen]

**Verantwortliche Person:** [eintragen und Freigabe dokumentieren]

**Unterschrift Geschäftsführung:**

_____________________________
Ort, Datum

_____________________________
Unterschrift, Name`,
            isAutoGenerated: false,
        },
    ];
}

/**
 * Create empty documentation data with defaults
 */
export function createEmptyDocumentation(): Omit<DocumentationData, 'createdAt' | 'updatedAt'> {
    return {
        companyName: '',
        companyAddress: '',
        taxNumber: '',
        responsiblePerson: '',
        sections: getDefaultDocumentationTemplate(),
        systemInfo: getSystemInfo(),
    };
}

/**
 * Get current app version
 */
export function getAppVersion(): string {
    return APP_VERSION;
}
