import { describe, expect, it } from 'vitest'
import { generateZugferdXml, type ZugferdData } from '../zugferd-generator'
import { getRawEInvoiceXml, parseEInvoiceXml } from '../e-invoice-parser'

function createZugferdData(overrides: Partial<ZugferdData> = {}): ZugferdData {
    return {
        invoiceNumber: 'RE-2025-001',
        date: new Date('2025-01-15'),
        dueDate: new Date('2025-02-14'),
        seller: {
            name: 'Bivaro Testfirma',
            address: 'Musterstraße 1\n12345 Musterstadt',
            email: 'rechnung@testfirma.de',
            taxNumber: '123/456/78901',
            iban: 'DE89370400440532013000',
        },
        buyer: {
            name: 'Kunde GmbH',
            address: 'Kundenweg 9',
            email: 'buchhaltung@kunde.de',
            zipCode: '54321',
            city: 'Kundenstadt',
        },
        items: [
            {
                description: 'Beratung',
                quantity: 2,
                unitPrice: 150,
                total: 300,
                unit: 'Stunde',
                taxRate: 0,
            },
        ],
        netAmount: 300,
        taxAmount: 0,
        currency: 'EUR',
        ...overrides,
    }
}

const ublInvoiceXml = `<?xml version="1.0" encoding="UTF-8"?>
<Invoice xmlns="urn:oasis:names:specification:ubl:schema:xsd:Invoice-2"
  xmlns:cac="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2"
  xmlns:cbc="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2">
  <cbc:CustomizationID>urn:cen.eu:en16931:2017</cbc:CustomizationID>
  <cbc:ID>XR-2025-77</cbc:ID>
  <cbc:IssueDate>2025-03-01</cbc:IssueDate>
  <cbc:DueDate>2025-03-15</cbc:DueDate>
  <cac:AccountingSupplierParty>
    <cac:Party>
      <cac:PartyName><cbc:Name>Lieferant GmbH</cbc:Name></cac:PartyName>
      <cac:PostalAddress>
        <cbc:StreetName>Lieferweg 1</cbc:StreetName>
        <cbc:CityName>Berlin</cbc:CityName>
        <cbc:PostalZone>10115</cbc:PostalZone>
        <cac:Country><cbc:IdentificationCode>DE</cbc:IdentificationCode></cac:Country>
      </cac:PostalAddress>
      <cac:Contact><cbc:ElectronicMail>invoice@lieferant.de</cbc:ElectronicMail></cac:Contact>
    </cac:Party>
  </cac:AccountingSupplierParty>
  <cac:AccountingCustomerParty>
    <cac:Party>
      <cac:PartyName><cbc:Name>Kunde AG</cbc:Name></cac:PartyName>
      <cac:PostalAddress>
        <cbc:StreetName>Kundenstraße 5</cbc:StreetName>
        <cbc:CityName>Hamburg</cbc:CityName>
        <cbc:PostalZone>20095</cbc:PostalZone>
        <cac:Country><cbc:IdentificationCode>DE</cbc:IdentificationCode></cac:Country>
      </cac:PostalAddress>
      <cac:Contact><cbc:ElectronicMail>rechnung@kunde-ag.de</cbc:ElectronicMail></cac:Contact>
    </cac:Party>
  </cac:AccountingCustomerParty>
  <cac:LegalMonetaryTotal>
    <cbc:LineExtensionAmount currencyID="EUR">120.00</cbc:LineExtensionAmount>
    <cbc:TaxInclusiveAmount currencyID="EUR">120.00</cbc:TaxInclusiveAmount>
    <cbc:PayableAmount currencyID="EUR">120.00</cbc:PayableAmount>
  </cac:LegalMonetaryTotal>
  <cac:InvoiceLine>
    <cbc:ID>1</cbc:ID>
    <cbc:InvoicedQuantity unitCode="HUR">3</cbc:InvoicedQuantity>
    <cbc:LineExtensionAmount currencyID="EUR">120.00</cbc:LineExtensionAmount>
    <cac:Item>
      <cbc:Name>Support</cbc:Name>
      <cac:ClassifiedTaxCategory><cbc:Percent>0</cbc:Percent></cac:ClassifiedTaxCategory>
    </cac:Item>
    <cac:Price><cbc:PriceAmount currencyID="EUR">40.00</cbc:PriceAmount></cac:Price>
  </cac:InvoiceLine>
</Invoice>`

describe('parseEInvoiceXml', () => {
    it('parses ZUGFeRD/Factur-X CII XML generated by the app', async () => {
        const xml = generateZugferdXml(createZugferdData())
        const parsed = await parseEInvoiceXml(xml)

        expect(parsed.format).toBe('CII')
        expect(parsed.invoiceNumber).toBe('RE-2025-001')
        expect(parsed.invoiceDate?.toISOString()).toContain('2025-01-15')
        expect(parsed.dueDate?.toISOString()).toContain('2025-02-14')
        expect(parsed.totalAmount).toBe(300)
        expect(parsed.customerName).toBe('Kunde GmbH')
        expect(parsed.buyerInfo).toMatchObject({
            email: 'buchhaltung@kunde.de',
            address: 'Kundenweg 9',
            zipCode: '54321',
            city: 'Kundenstadt',
            country: 'DE',
        })
        expect(parsed.sellerInfo.name).toBe('Bivaro Testfirma')
        expect(parsed.lineItems).toEqual([
            expect.objectContaining({
                positionNumber: '1',
                description: 'Beratung',
                quantity: 2,
                unit: 'HUR',
                unitPrice: 150,
                amount: 300,
                taxRate: 0,
            }),
        ])
        expect(parsed.rawXml).toContain('<rsm:CrossIndustryInvoice')
    })

    it('parses standalone XRechnung UBL invoice XML', async () => {
        const parsed = await parseEInvoiceXml(ublInvoiceXml)

        expect(parsed.format).toBe('UBL')
        expect(parsed.invoiceNumber).toBe('XR-2025-77')
        expect(parsed.invoiceDate?.toISOString()).toContain('2025-03-01')
        expect(parsed.dueDate?.toISOString()).toContain('2025-03-15')
        expect(parsed.totalAmount).toBe(120)
        expect(parsed.customerName).toBe('Kunde AG')
        expect(parsed.buyerInfo).toMatchObject({
            email: 'rechnung@kunde-ag.de',
            address: 'Kundenstraße 5',
            zipCode: '20095',
            city: 'Hamburg',
            country: 'DE',
        })
        expect(parsed.sellerInfo.name).toBe('Lieferant GmbH')
        expect(parsed.lineItems[0]).toMatchObject({
            positionNumber: '1',
            description: 'Support',
            quantity: 3,
            unit: 'HUR',
            unitPrice: 40,
            amount: 120,
            taxRate: 0,
        })
    })

    it('rejects unsupported XML structures', async () => {
        await expect(parseEInvoiceXml('<root><id>1</id></root>')).rejects.toThrow('Unbekannte E-Rechnungsstruktur')
    })
})

describe('getRawEInvoiceXml', () => {
    it('returns stored raw XML from objects and JSON strings', () => {
        expect(getRawEInvoiceXml({ rawXml: '<Invoice />' })).toBe('<Invoice />')
        expect(getRawEInvoiceXml(JSON.stringify({ rawXml: '<Invoice />' }))).toBe('<Invoice />')
    })

    it('returns null when no raw XML is available', () => {
        expect(getRawEInvoiceXml({ rawXml: 'not xml' })).toBeNull()
        expect(getRawEInvoiceXml('{invalid json')).toBeNull()
        expect(getRawEInvoiceXml(null)).toBeNull()
    })
})
